name: EVM E2E tests

# Run on PRs
on:
  pull_request:

# Allow concurrent runs on main/release branches but isolates other branches
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  e2e-evm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Check for EVM-related changes"
        id: check_evm_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            evm-changes:
              - "app/**/*.go"
              - "cmd/**/*.go"
              - "eth/**/*.go"
              - "gosdk/**/*.go"
              - "x/**/*.go"
              - "**/*.proto"
              - "**go.mod"
              - "**go.sum"
              - "contrib/docker-compose/*"
              - "**.ts"
              - "**.js"
              - "**.json"

      - name: skip-tests
        if: steps.check_evm_changes.outputs.evm-changes == 'false'
        run: |
          echo "job: e2e-evm was skipped since relevant files were not changed."

      - name: Set up Go
        if: steps.check_evm_changes.outputs.evm-changes == 'true'
        uses: actions/setup-go@v6
        with:
          go-version: 1.24
          # cache: "The action has a built-in functionality for caching and
          # restoring go modules and build outputs. It uses [actions/cache@v4]."
          # - Handles go module cache (go env GOMODCACHE).
          # - Handles go build cache (go env GOCACHE).
          cache: true

      - name: "Install just"
        if: steps.check_evm_changes.outputs.evm-changes == 'true'
        # casey/just: https://just.systems/man/en/chapter_6.html
        # taiki-e/install-action: https://github.com/taiki-e/install-action
        uses: taiki-e/install-action@just

      - name: "Build the nibid binary"
        if: steps.check_evm_changes.outputs.evm-changes == 'true'
        run: |
          just install

      - name: Setup NodeJS with npm caching
        if: steps.check_evm_changes.outputs.evm-changes == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: "lts/jod"
          cache-dependency-path: "evm-e2e/package-lock.json"

      - name: "just install"
        if: steps.check_evm_changes.outputs.evm-changes == 'true'
        run: just install
        working-directory: "evm-e2e"

      - name: "Launch localnet"
        if: steps.check_evm_changes.outputs.evm-changes == 'true'
        run: |
          just localnet --no-build &
          sleep 10

      - name: "Run tests (just test)"
        if: steps.check_evm_changes.outputs.evm-changes == 'true'
        run: |
          just install
          just test
        working-directory: "evm-e2e"
        env:
          JSON_RPC_ENDPOINT: http://127.0.0.1:8545
          MNEMONIC: guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host

  sai-trading:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Check for EVM-related changes"
        id: check_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            check_changes:
              - "sai-trading/**/*.ts"
              - "sai-trading/artifacts/*"
              - "sai-trading/**/*.go"

      - name: Set up Go
        if: steps.check_changes.outputs.check_changes == 'true'
        uses: actions/setup-go@v6
        with:
          go-version: 1.24
          # cache: "The action has a built-in functionality for caching and
          # restoring go modules and build outputs. It uses [actions/cache@v4]."
          # - Handles go module cache (go env GOMODCACHE).
          # - Handles go build cache (go env GOCACHE).
          cache: true

      - name: "Install just"
        if: steps.check_changes.outputs.check_changes == 'true'
        # casey/just: https://just.systems/man/en/chapter_6.html
        # taiki-e/install-action: https://github.com/taiki-e/install-action
        uses: taiki-e/install-action@just

      - name: "Build the nibid binary"
        if: steps.check_changes.outputs.check_changes == 'true'
        run: |
          just install

      - if: steps.check_changes.outputs.check_changes == 'true'
        # For running things and for package management "
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.22 # Values: latest, <sha>, 1.2.3, canary
        # Outputs:
        # - cache-hit    : Whether the executable was read from cache. Ex. "true"
        # - bun-version  : The output from running `bun-version`. Ex. "1.0.0"
        # - bun-revision : The output from running `bun-revision`.

      - if: steps.check_changes.outputs.check_changes == 'true'
        working-directory: "sai-trading"
        run: |
          bun install

      - if: steps.check_changes.outputs.check_changes == 'true'
        run: |
          just localnet --no-build &
          sleep 10

      - if: steps.check_changes.outputs.check_changes == 'true'
        working-directory: "sai-trading"
        run: |
          just test
