name: PR lint

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@main
        with:
          # taken from https://gist.github.com/marcojahn/482410b728c31b221b70ea6d2c433f0c
          title-regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)'
          title-regex-flags: "g" # optional
          error-message: "Please follow conventional commit style: https://www.conventionalcommits.org/en/v1.0.0/" # optional
