# skip-proto-gen.yml runs when proto-gen.yml is skipped
name: Proto Generation

on:
  pull_request:
    # paths-ignore makes the action run when the given paths are unchanged
    # See "Handling skipped but required checks" in
    # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
    paths-ignore: ["**.proto", "**protocgen**"]
  
jobs:
  proto-gen:
    runs-on: ubuntu-latest
    steps:
    - name: skip-tests
      run: |
        echo "proto-gen.yml skipped since proto files were not changed."