name: Upgrade Handler Check

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  check-upgrade-handler:
    name: Validate Upgrade Handler exists
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure git for private modules
        run: |
          git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"
          echo "GOPRIVATE=github.com/cometbft/*" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run Upgrade Handler Checker
        run: |
          go run ./contrib/scripts/upgrade-handler-check.go "${{ github.ref_name }}"